# Generated by Django 4.2.16 on 2024-09-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra_field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('extrafieldmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extra_field.extrafieldmodel')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            bases=('extra_field.extrafieldmodel',),
        ),
    ]
